# Generated by Django 3.2.25 on 2025-11-14 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], max_length=10)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('other', 'Other')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
